#!/usr/bin/python3
# vim:se tw=0 sts=4 ts=4 sw=4 et ai:
"""
Copyright © 2024 Osamu Aoki

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA
"""
# For main
import argparse
import csv
import locale

# For sub-commands
import os
import os.path

#######################################################################
# ZEN HAN conversion table (exclude comma and include space)
#######################################################################
ZEN = "".join(chr(0xFF01 + i) for i in range(94)).replace("，", "　")
HAN = "".join(chr(0x21 + i) for i in range(94)).replace(",", " ")

ZEN2HAN = str.maketrans(ZEN, HAN)


#######################################################################
# set default account to be assigned
#######################################################################
def check_match(rowx1, name):
    # match starting portion
    return rowx1[: len(name)] == name


def check_substr(rowx1, name):
    return name in rowx1


def update_rowx4(rowx):
    rowx4 = rowx[4]
    if (
        check_match(rowx[1], "AMAZON.CO.JP")
        or check_match(rowx[1], "大丸")
        or check_match(rowx[1], "神戸阪急")
    ):
        if check_substr(rowx[1], "化粧品"):
            rowx4 = "5化粧品"
        elif check_substr(rowx[1], "婦人") or check_substr(rowx[1], "紳士"):
            rowx4 = "3衣料品"
        elif int(rowx[2]) < 3000:
            rowx4 = "1生活費"
        else:
            rowx4 = "不明-JPY"
    if (
        check_match(rowx[1], "イスズ")
        or check_match(rowx[1], "カルディ")
        or check_match(rowx[1], "業務スーパー")
    ):
        if int(rowx[2]) < 10000:
            rowx4 = "1生活費"
        else:
            rowx4 = "不明-JPY"
    if check_match(rowx[1], "ユニクロ"):
        rowx4 = "3衣料品"
    if "医院" in rowx[1] or "ビヨウイン" in rowx[1] or "クリニック" in rowx[1] or "薬局" in rowx[1]:
        rowx4 = "4医療費"
    if "ガス利用料金" in rowx[1]:
        rowx4 = "費用:公:ガス"
    if "水道局" in rowx[1]:
        rowx4 = "費用:公:水道"
    if "電気料金" in rowx[1]:
        rowx4 = "費用:公:電気"
    # 必ずnon-NULL return
    if rowx4 == "":
        if int(rowx[2]) < 2000:
            rowx4 = "1生活費"
        else:
            rowx4 = "不明-JPY"
    return rowx4


#######################################################################
# main: parse command line parser
#######################################################################
def main():
    locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""\
VISA/DAIMARUカードデーターの前処理フィルター

これは、実際に使用しているスクリプトから、個人的状況詳細が絡む処理関連部分を削除し
て簡素化した公開用のスケルトンバージョンです。

VISAカードの使用履歴はcsvダウンロードできるのは良いのですが、そのまま
GnuCacheに読み込むとなんとも使い勝手がよろしくありません。

本フィルターは、一部情報は失われますが、月末のカード支払いの仕分けス
ムーズにができるようにcsvを再構成します。

合わせて、エンコーディングをSJISからUTF-8にし、全角数字英字は半角化し、
半角スペース連続２は１にします。(全角カタカナ、コンマは無変換)

25日〆確定とは、26日からデーターが入手可能。

一般VISA 25日〆確定　支払い明細元ファイルのカラム構成　（＊のみ処理、すべて１回払で扱う）
0: ご利用日 ＊ (""行は無視、"青木　修"行以外は家族扱い)
1: ご利用店名 ＊
2: ご利用金額
3: 支払区分
4: 分割回数
5: お支払金額
7: お支払い総額 現地通貨額
: お支払い総額 略称
: 内手数料 換算レート
: 内手数料 換算日

DAIMARU 25日〆確定　支払い明細元ファイルのカラム構成　（＊のみ処理、すべて１回払で扱う）
0: 支払変更　（データー行の場合）　最初行が"4980-"でスタート
1: ご利用日　＊
2: ご利用店　＊　（大丸かどうかのみ）
3: ご利用明細　＊　（関連行を合わせる）
4: 支払区分
5: ご利用金額
6: 内入金
7: 支払回数
8: お支払総額　＊
9: 外貨処理

デパート系は割引やポイント利用などが複数行に渡って記載されるので、それをGnuCashに合うように
整形することも行っています。

一般 未定　支払い予定元ファイルのカラム構成　（＊のみ処理、すべて１回払で扱う）
0: ご利用日 ＊
1: ご利用店名 ＊
2: カード (ご本人？)　＊
3: 支払区分
4: 分割回数
5: 支払予定月
6: ご利用金額 (日本円相当)
7: ご利用金額（日本円）
8: お支払い総額 現地通貨額
9: お支払い総額 略称
10: 内手数料 換算レート
11: 内手数料 換算日

標準出力
0: 利用日
1: 説明　＝　利用明細 (本人以外は" *")
2: 利用金額
3: 補足
4: 資金移動先勘定項目

copyright 2024 Osamu Aoki <osamu@debian.org>
license: GPL 2.0+

""",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", default=False, help="饒舌モード"
    )
    parser.add_argument("csv", help="ダウンロードされたCSVファイル名")
    parser.set_defaults(func=help, parser=parser)
    #######################################################################
    # generate argument parser instance
    #######################################################################
    args = parser.parse_args()
    verbose = args.verbose
    #######################################################################
    # Update variables with sanitization
    #######################################################################
    data_phase = ""
    user_suffix = ""
    card_type = "VISA"
    usage_string = ""
    account_index = 0
    with open(os.path.splitext(args.csv)[0] + ".out.csv", "w", newline="") as csvout:
        datawriter = csv.writer(csvout, dialect="excel")
        with open(args.csv, "r", newline="", encoding="SJIS") as csvin:
            datareader = csv.reader(csvin, dialect="excel")
            for i, row in enumerate(datareader):
                rowx = ["", "", 0, "", ""]  # initialize
                if row[0] == "":
                    if verbose:
                        print("{}: columns={} <EMPTY>".format(i, len(row)))
                    pass  # ignore
                elif (
                    ord(row[0][0]) >= 0x2000 and card_type == "VISA"
                ):  # 一般VISA 確定（全角で始まる）
                    card_type = "VISA"
                    data_phase = "final"
                    if verbose:
                        print(
                            "{}: columns={} <SET-VISA-FINAL> {}".format(
                                i, len(row), row[:10]
                            )
                        )
                    if account_index == 0:
                        user_suffix = ""
                    else:
                        user_suffix = " " + "*" * account_index
                    account_index += 1
                elif len(row[0]) >= 12:  # 大丸カード番号 は長い（12文字以上）
                    card_type = "DAIMARU"
                    data_phase = "final"
                    if verbose:
                        print(
                            "{}: columns={} <SET-DAIMARU-FINAL> {}".format(
                                i, len(row), row[:10]
                            )
                        )
                    if account_index == 0:
                        user_suffix = ""
                    else:
                        user_suffix = " " + "*" * account_index
                    pass  # ignore
                    account_index += 1
                elif data_phase == "final" and card_type == "VISA":
                    if verbose:
                        print(
                            "{}: columns={} <VISA-FINAL> {}".format(
                                i, len(row), row[:10]
                            )
                        )
                    rowx[0] = row[0]
                    rowx[1] = row[1].translate(ZEN2HAN).replace("  ", " ") + user_suffix
                    rowx[2] = row[5]
                    if len(row) >= 7 and row[6] != "":
                        rowx[3] = "final " + row[6].translate(ZEN2HAN).replace(
                            "  ", " "
                        )
                    else:
                        rowx[3] = "final"
                    rowx[4] = update_rowx4(rowx)
                    datawriter.writerow(rowx)
                elif data_phase == "final" and card_type == "DAIMARU":
                    if verbose:
                        print(
                            "{}: columns={} <DAIMARU-FINAL> {}".format(
                                i, len(row), row[:10]
                            )
                        )
                    rowx[0] = row[1]
                    if row[8] == "":  # 以下の行とまとめる
                        usage_string = usage_string + "+" + row[3]
                    else:
                        if row[3] != "割引額":  # 単純ケース
                            if row[2] != "":  # 店番号
                                rowx[1] = (
                                    "大丸"
                                    + row[2]
                                    + ":"
                                    + row[3].translate(ZEN2HAN).replace("  ", " ")
                                    + user_suffix
                                )
                            else:
                                rowx[1] = (
                                    row[3].translate(ZEN2HAN).replace("  ", " ")
                                    + user_suffix
                                )
                        else:  # 割引行
                            if row[2] != "":  # 店番号
                                rowx[1] = (
                                    "大丸"
                                    + row[2]
                                    + ":"
                                    + usage_string[1:]
                                    .translate(ZEN2HAN)
                                    .replace("  ", " ")
                                    + user_suffix
                                )
                            else:
                                rowx[1] = (
                                    "ERROR-割引額 "
                                    + usage_string[1:]
                                    .translate(ZEN2HAN)
                                    .replace("  ", " ")
                                    + user_suffix
                                )
                            usage_string = ""
                        rowx[2] = row[8]
                        if len(row) >= 10 and row[9] != "":
                            rowx[3] = "final " + row[9].translate(ZEN2HAN).replace(
                                "  ", " "
                            )
                        else:
                            rowx[3] = "final"
                        rowx[4] = update_rowx4(rowx)
                        datawriter.writerow(rowx)
                else:  # data_phase == "" -- 予定支出額
                    if verbose:
                        print("{}: columns={} <PLAN> {}".format(i, len(row), row[:10]))
                    rowx[0] = row[0]
                    if row[2] == "ご本人":
                        user_suffix = ""
                    else:
                        user_suffix = " *"
                    rowx[1] = row[1].translate(ZEN2HAN).replace("  ", " ") + user_suffix
                    if row[7] != "":
                        rowx[2] = row[7]  # カード払い分のみ (ポイント分を引いた値の記載あり)
                    else:
                        rowx[2] = row[6]  # 全支払い＝カード払い総額の場合
                    # print("6th={} 7th={}".format( row[6], row[7]))
                    if len(row) > 10:  # final are 3-10, plan is 13
                        rowx[3] = (
                            " ".join(row[9:]).translate(ZEN2HAN).replace("  ", " ")
                        )
                    else:
                        rowx[3] = ""
                    rowx[2] = rowx[2].translate(ZEN2HAN).replace("  ", " ")
                    rowx[4] = update_rowx4(rowx)
                    rowx[1] = "仮 " + rowx[1]
                    datawriter.writerow(rowx)
    return


#######################################################################
# Test code
#######################################################################
if __name__ == "__main__":
    main()
